"""Review: assemble the bundle, record the verdict, judge nothing.

The gate proves the code does what the checks say. It cannot say the checks
were the right ones, or that the change is three times bigger than the
problem. That gap is real and no exit code closes it.

What this module does NOT do is close it automatically. Handing the diff to a
model and accepting the answer would move judgement into the machine, and the
whole argument here is that judgement is the part that cannot be automated -
a reviewer the harness invokes and believes is just the agent grading itself
with extra steps.

So the split is:

  the harness   assembles the bundle, and records that a human ruled
  a human       reads, decides, and types the verdict

The trace records **that you reviewed and what you decided** - never a
verdict a model produced. If it did, `require_review` would be satisfiable by
a model that never read anything.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

BUNDLE = "review-bundle.md"
VERDICTS = ("ship", "hold")

HEADER = """\
<!-- Generated by `harness review`. Not for committing. -->

Open a session with **no history of this work** and paste this whole file.

Not the build log, not the reasoning that produced the change. Context that
explains why the author did something is exactly the context that stops a
reviewer noticing they should not have.

When you have the answer, record it:

    harness review --record ship --note "..."
    harness review --record hold --note "..."

---

"""


def diff(cwd: Path, base: str) -> str | None:
    """The change under review. None when git cannot answer."""
    for args in (["diff", f"{base}...HEAD"], ["diff", base]):
        try:
            proc = subprocess.run(
                ["git", *args], cwd=cwd, capture_output=True, text=True, timeout=120
            )
        except (OSError, subprocess.TimeoutExpired):
            return None
        if proc.returncode == 0 and proc.stdout.strip():
            return proc.stdout
    return None


def bundle(cwd: Path, prompt: str, spec: str | None, change: str, base: str) -> str:
    parts = [HEADER, "## The prompt\n\n", prompt.strip(), "\n\n---\n\n"]
    if spec:
        parts += ["## The spec\n\n```markdown\n", spec.strip(), "\n```\n\n---\n\n"]
    parts += [f"## The diff (`{base}...HEAD`)\n\n```diff\n", change.strip(), "\n```\n"]
    return "".join(parts)


def extract_prompt(reviewer_md: str) -> str:
    """The fenced block under '## The prompt', so the bundle carries the
    prompt itself rather than the prose explaining it."""
    marker = "## The prompt"
    if marker in reviewer_md:
        after = reviewer_md.split(marker, 1)[1]
        if "```" in after:
            return after.split("```", 2)[1].strip()
    return reviewer_md.strip()


def reviewed(trace, base_sha: str) -> dict:
    """Has this exact revision been reviewed, and what was decided?

    Keyed on the commit, so a review does not silently carry over to later
    work. Reviewing once and then pushing three more commits is the failure
    this prevents.
    """
    for row in reversed(list(trace.rows())):
        if row.get("phase") != "review":
            continue
        if row.get("cmd") != base_sha:
            continue
        verdict = "ship" if row.get("ok") else "hold"
        return {"reviewed": True, "verdict": verdict, "note": row.get("evidence", ""), "ts": row.get("ts", "")}
    return {"reviewed": False, "verdict": None, "note": "", "ts": ""}


def head_sha(cwd: Path) -> str | None:
    try:
        proc = subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=cwd, capture_output=True, text=True, timeout=60
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    return proc.stdout.strip() if proc.returncode == 0 else None
